<?php

use Drupal\Core\Url;

function structured_data_toolbar_alter(&$items) {
	$user = \Drupal::currentUser();

	if ($user->hasPermission('manage page structured data json')) {
		//https://www.drupal.org/node/2382211
		$url = Url::fromRoute('<current>')->toString();
		$querystring = \Drupal::getContainer()->get('request_stack')->getCurrentRequest()->getQueryString();
		if(!empty($querystring)) {
			$url = $url + '?' + $querystring;
		}
		$url = base64_encode($url);
		$url = str_replace('/', '|', $url);
		
		$links = array(
			'sd_json' => array(
				'title' => t('Page Json'),
				'url' => Url::fromRoute('structured_data.page.json', ['sd_route_name' => \Drupal::routeMatch()->getRouteName(), 'sd_url' => $url]),
				'attributes' => array(
					'title' => t('Page structured data json'),
					'class' => ['structured-data-page-json-link'],
					'data-url-template' => Url::fromRoute('structured_data.page.json', ['sd_route_name' => \Drupal::routeMatch()->getRouteName(), 'sd_url' => '--template--'])->toString(),
				),
				'#cache' => [
				  'contexts' => ['user', 'url'],
				],
			),
		);		

		$items['shortcuts']['tray']['shortcuts']['#links'] += $links;
	}
}

function structured_data_page_attachments_alter(array &$attachments) {
	$user = \Drupal::currentUser();
	$route_name = \Drupal::routeMatch()->getRouteName();
	$url = Url::fromRoute('<current>')->toString();
	
	$jsonObj = \Drupal\structured_data\Core\Helper::getPageJson($route_name, $url);
	if ($jsonObj == NULL) {
		$jsonObj = \Drupal\structured_data\Core\Helper::getPageJson($route_name);
	}
	
	if ($jsonObj != NULL) {
		$tag = [
			'#type' => 'html_tag',
			'#tag' => 'script',
			'#attributes' => [
				'type' => 'application/ld+json',
			],
			'#value' => $jsonObj->json,
		];

		$attachments['#attached']['html_head'][] = [$tag, 'structured_data_json'];
	}

	if ($user->hasPermission('manage page structured data json')) {
		$attachments['#attached']['library'][] = 'structured_data/toolbar';
	}
}
